//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugShooting.Output.InformUp.InformUp.WorkItem {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InformUp.WorkItem.WorkItemSoap")]
    public interface WorkItemSoap {
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname sUserLoginName aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileResponse UploadFile(BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileResponse> UploadFileAsync(BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname sUserLoginName aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWorkItem", ReplyAction="*")]
        BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemResponse AddWorkItem(BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWorkItem", ReplyAction="*")]
        System.Threading.Tasks.Task<BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemResponse> AddWorkItemAsync(BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname sUserLoginName aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVersion", ReplyAction="*")]
        BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionResponse GetVersion(BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionResponse> GetVersionAsync(BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://tempuri.org/", Order=0)]
        public BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserLoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sUserPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] f;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int iWorkItem;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(string sUserLoginName, string sUserPassword, byte[] f, string fileName, int iWorkItem) {
            this.sUserLoginName = sUserLoginName;
            this.sUserPassword = sUserPassword;
            this.f = f;
            this.fileName = fileName;
            this.iWorkItem = iWorkItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddWorkItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddWorkItem", Namespace="http://tempuri.org/", Order=0)]
        public BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequestBody Body;
        
        public AddWorkItemRequest() {
        }
        
        public AddWorkItemRequest(BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddWorkItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserLoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sUserPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkItemType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description;
        
        public AddWorkItemRequestBody() {
        }
        
        public AddWorkItemRequestBody(string sUserLoginName, string sUserPassword, string WorkItemType, string Title, string Description) {
            this.sUserLoginName = sUserLoginName;
            this.sUserPassword = sUserPassword;
            this.WorkItemType = WorkItemType;
            this.Title = Title;
            this.Description = Description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddWorkItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddWorkItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemResponseBody Body;
        
        public AddWorkItemResponse() {
        }
        
        public AddWorkItemResponse(BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddWorkItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddWorkItemResult;
        
        public AddWorkItemResponseBody() {
        }
        
        public AddWorkItemResponseBody(string AddWorkItemResult) {
            this.AddWorkItemResult = AddWorkItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="http://tempuri.org/", Order=0)]
        public BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequestBody Body;
        
        public GetVersionRequest() {
        }
        
        public GetVersionRequest(BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserLoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sUserPassword;
        
        public GetVersionRequestBody() {
        }
        
        public GetVersionRequestBody(string sUserLoginName, string sUserPassword) {
            this.sUserLoginName = sUserLoginName;
            this.sUserPassword = sUserPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionResponseBody Body;
        
        public GetVersionResponse() {
        }
        
        public GetVersionResponse(BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVersionResult;
        
        public GetVersionResponseBody() {
        }
        
        public GetVersionResponseBody(string GetVersionResult) {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorkItemSoapChannel : BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkItemSoapClient : System.ServiceModel.ClientBase<BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap>, BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap {
        
        public WorkItemSoapClient() {
        }
        
        public WorkItemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkItemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkItemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkItemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileResponse BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap.UploadFile(BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(string sUserLoginName, string sUserPassword, byte[] f, string fileName, int iWorkItem) {
            BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequest inValue = new BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequest();
            inValue.Body = new BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequestBody();
            inValue.Body.sUserLoginName = sUserLoginName;
            inValue.Body.sUserPassword = sUserPassword;
            inValue.Body.f = f;
            inValue.Body.fileName = fileName;
            inValue.Body.iWorkItem = iWorkItem;
            BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileResponse retVal = ((BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileResponse> BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap.UploadFileAsync(BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequest request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileResponse> UploadFileAsync(string sUserLoginName, string sUserPassword, byte[] f, string fileName, int iWorkItem) {
            BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequest inValue = new BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequest();
            inValue.Body = new BugShooting.Output.InformUp.InformUp.WorkItem.UploadFileRequestBody();
            inValue.Body.sUserLoginName = sUserLoginName;
            inValue.Body.sUserPassword = sUserPassword;
            inValue.Body.f = f;
            inValue.Body.fileName = fileName;
            inValue.Body.iWorkItem = iWorkItem;
            return ((BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap)(this)).UploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemResponse BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap.AddWorkItem(BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequest request) {
            return base.Channel.AddWorkItem(request);
        }
        
        public string AddWorkItem(string sUserLoginName, string sUserPassword, string WorkItemType, string Title, string Description) {
            BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequest inValue = new BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequest();
            inValue.Body = new BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequestBody();
            inValue.Body.sUserLoginName = sUserLoginName;
            inValue.Body.sUserPassword = sUserPassword;
            inValue.Body.WorkItemType = WorkItemType;
            inValue.Body.Title = Title;
            inValue.Body.Description = Description;
            BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemResponse retVal = ((BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap)(this)).AddWorkItem(inValue);
            return retVal.Body.AddWorkItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemResponse> BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap.AddWorkItemAsync(BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequest request) {
            return base.Channel.AddWorkItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemResponse> AddWorkItemAsync(string sUserLoginName, string sUserPassword, string WorkItemType, string Title, string Description) {
            BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequest inValue = new BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequest();
            inValue.Body = new BugShooting.Output.InformUp.InformUp.WorkItem.AddWorkItemRequestBody();
            inValue.Body.sUserLoginName = sUserLoginName;
            inValue.Body.sUserPassword = sUserPassword;
            inValue.Body.WorkItemType = WorkItemType;
            inValue.Body.Title = Title;
            inValue.Body.Description = Description;
            return ((BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap)(this)).AddWorkItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionResponse BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap.GetVersion(BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequest request) {
            return base.Channel.GetVersion(request);
        }
        
        public string GetVersion(string sUserLoginName, string sUserPassword) {
            BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequest inValue = new BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequest();
            inValue.Body = new BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequestBody();
            inValue.Body.sUserLoginName = sUserLoginName;
            inValue.Body.sUserPassword = sUserPassword;
            BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionResponse retVal = ((BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap)(this)).GetVersion(inValue);
            return retVal.Body.GetVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionResponse> BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap.GetVersionAsync(BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequest request) {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionResponse> GetVersionAsync(string sUserLoginName, string sUserPassword) {
            BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequest inValue = new BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequest();
            inValue.Body = new BugShooting.Output.InformUp.InformUp.WorkItem.GetVersionRequestBody();
            inValue.Body.sUserLoginName = sUserLoginName;
            inValue.Body.sUserPassword = sUserPassword;
            return ((BugShooting.Output.InformUp.InformUp.WorkItem.WorkItemSoap)(this)).GetVersionAsync(inValue);
        }
    }
}
